#!/bin/bash


# This scripe is designed to do this 
# Author: Ella Thomasson 
# Last updated 2/6/24 

read -p "What is your favorite number?" FAVNUM
echo "Hey $USER I heard your favorite number is $FAVNUM"
